### ISSUE TITLE
isbn_ren fails if filename has the dash (-) character

### ISSUE THREAD

**Issue by dd066** [xlcnd/isbntools#103]
Hello,

To reproduce the bug, create a text file with the following name:
"Small, Sharp, Software Tools-Hogan-2019-9781680502961.txt"

The command:
isbn_ren "{title}-{firstAuthorLastName}-{year} -ISBN13 {isbn}" *.txt
will return
"no ISBN found in name of file Small, Sharp, Software Tools-Hogan-2019-9781680502961.txt"

If you add a space for instance just before the dash, it works.

BR,
David

**Comment by xlcnd** [comment]
Thanks! This is a problem in `isbnlib`. I will fix it in the next release.
