### ISSUE TITLE
Documentation for usage in python

### ISSUE THREAD

**Issue by GeorgAubele** [xlcnd/isbntools#122]
I know the isbntools are primarily for command line usage. But as the package is available for python, I'm missing a doc file for the usage in python code. 
I would help to write that doc , if - in the first place - I know which of the commands are available in python and how to use them.
Can you point me to a source for it? I'm not that experienced as a dev, but I did not find enough information in the source code.

**Comment by xlcnd** [comment]
Hi!

That information is already in many places like:

1. [pypi](https://pypi.org/project/isbntools/)
2. [github](https://github.com/xlcnd/isbntools/blob/dev/README.rst)
3. [readthedocs](https://isbntools.readthedocs.io/en/latest/)
