### ISSUE TITLE
easy_install - error

### ISSUE THREAD

**Issue by wschrabi** [xlcnd/isbntools#86]
Hi, I tried to install the latest isbntools with easy_install and got that error desc. in stackoverflow: 
http://stackoverflow.com/questions/30217681/sandboxviolation-error-when-installing-isbntools-with-easy-install

Can you help me? I could not pip installed - I must use easy_install.

**Comment by xlcnd** [comment]
Take a look at http://stackoverflow.com/a/30299741/451925

**Comment by xlcnd** [comment]
For another solution take a look at #87 .

**Comment by wschrabi** [comment]
thanks, works now fine!

Am 22.05.2015 um 17:44 schrieb Alexandre Conde:
