### ISSUE TITLE
Make a 'system install' of 'isbntools' manually (for sandboxed systems)

### ISSUE THREAD

**Issue by xlcnd** [xlcnd/isbntools#87]
Some systems like SUSE SLES are sandboxed so that installers like (`easy_install` or `pip`) cannot write in user's area (**just for system's installs**!).

The alternative is to use virtual environments or an user's install!

However, if by any reason you want to make a system install of `isbntools` try the following procedure:
1. `wget https://pypi.python.org/packages/source/i/isbntools/isbntools-4.3.4.tar.gz`
2. `tar xvfz isbntools-4.3.4.tar.gz` 
3. `cd isbntools-4.3.4`
4. replace the content of `setup.py` with this:

``` python
from setuptools import find_packages, setup

setup(
    name='isbntools',
    version='4.3.4',
    author='xlcnd',
    author_email='xlcnd@outlook.com',
    url='https://github.com/xlcnd/isbntools',
    packages=find_packages(exclude=["*.test", "*.test.*", "test.*", "test"]),
    entry_points={
        'console_scripts': ['isbn_conf=isbntools.bin.confc:main',
                            'isbn_doi=isbntools.bin.doi:main',
                            'isbn_doi2tex=isbntools.bin.doi2tex:main',
                            'isbn_EAN13=isbntools.bin.EAN13:main',
                            'isbn_editions=isbntools.bin.editions:main',
                            'isbn_from_words=isbntools.bin.from_words:main',
                            'isbn_goom=isbntools.bin.goom:main',
                            'isbn_info=isbntools.bin.info:main',
                            'isbn_mask=isbntools.bin.mask:main',
                            'isbn_meta=isbntools.bin.meta:main',
                            'isbn_ren=isbntools.bin.ren:main',
                            'to_isbn10=isbntools.bin.to_isbn10:main',
                            'to_isbn13=isbntools.bin.to_isbn13:main',
                            'isbn_validate=isbntools.bin.validate:main',
                            'isbn_stdin_validate=isbntools.bin.validate:do_pipe',
                            'isbntools=isbntools.bin.version:main',
                            'isbn_repl=isbntools.bin.repl:main',
                            'isbn_cover=isbntools.bin.cover:main',
                            'isbn_desc=isbntools.bin.desc:main',
                            ]},
    install_requires=['isbnlib>=3.6.7, <3.7.1'],
    license='LGPL v3',
)
```
1. `python setup.py install` (`sudo python setup.py install` if you got errors!)
2. `cd .. && rm -r isbntools-4.3.4`
3. `mkdir ~/.isbntools`

And thats all! On first run, `isbntools` will try to create sensible default config files.

**Comment by ri0t** [comment]
This is now a problem on Debian as well. Just found this popping upon maintaining my dockerfile - oh, and pip3 itself was complaining about it. Didn't want to touch stuff in /root.

**Comment by xlcnd** [comment]
The best option is to install it always inside a (python) virtual environment!

**Comment by ri0t** [comment]
I always do so, but now get an error:
`    No such file or directory: '/home/riot/.virtualenvs/hfos/isbntools/isbntools.log'`

**Comment by xlcnd** [comment]
I am not able to reproduce the error... 

This error happens when you are installing the package or when you are using the app?
