### ISSUE TITLE
isbn_stdin_validate produces false positives

### ISSUE THREAD

**Issue by workflowsguy** [xlcnd/isbntools#89]
It would be great if the accuracy of the detection method could be improved.
E.g. in one case "4616709947" is reported as an ISBN but when I search for this in the source text, I see that it is in fact part of the number "0.461670994758606"

**Comment by xlcnd** [comment]
Hi,

This is a known issue, maybe in a future version the script will get a 'strict' option to avoid this...

Thanks.
