### ISSUE TITLE
Can't install when running Python3.6

### ISSUE THREAD

**Issue by coetzeevs** [xlcnd/isbntools#91]
I get this error when running pip install in python3.6:

Collecting isbntools
  Downloading isbntools-4.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-q2w4mxdu/isbntools/setup.py", line 55, in <module>
        __version__)
    Exception: isbntools 4.3.5  requires Python 2.6+ or 3.3+.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-q2w4mxdu/isbntools/

Any ideas of the cause? Thanks

**Comment by xlcnd** [comment]
There is an error in the configuration files that doesn't allow the package to install under python 3.6 in some platforms! 

I am sorry for that. I will fix the problem soon (probably tomorrow).

Thanks.

**Comment by coetzeevs** [comment]
Awesome!. Actually not a rush, came across your package while dreaming up a home project. Thought it could shorten data entry time when recording a list of books in a database we keep on the shelf (my wife likes keeping track of everything in that way). Thanks!
