### ISSUE TITLE
pip install isbntools-4.3.6.tar.gz throws error

### ISSUE THREAD

**Issue by devchristianschroeder** [xlcnd/isbntools#92]
I want to install the isbntools via 'pip install isbntools-4.3.6.tar.gz' and get the following error:

      File "c:\python\python36-32\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/home/alexandre/Code/ISBN/isbntools/isbntools.conf' cannot be absolute

Environment: Win10 x64 + Pyhton 3.6.2

![isbninstall](https://user-images.githubusercontent.com/25476817/29414559-5eb81bd8-8360-11e7-8c1c-ee1f742edb53.PNG)

**Comment by xlcnd** [comment]
Oops, this is a `setuptools` error! 

Please, use the github release https://github.com/xlcnd/isbntools/archive/v4.3.6.zip instead.
