### ISSUE TITLE
Every ISBNtools command throws FileNotFoundError for isbntools.log

### ISSUE THREAD

**Issue by workflowsguy** [xlcnd/isbntools#93]
I have just installed ISBNtools 4.3.7 with `Pip3 install isbntools`.

With every ISBNtools command I call, it fails with

```
Traceback (most recent call last):
  File "/usr/local/bin/isbn_conf", line 7, in <module>
    from isbntools.bin.confc import main
  File "/usr/local/lib/python3.6/site-packages/isbntools/bin/confc.py", line 10, in <module>
    from ..app import CACHE_FILE, CONF_PATH, quiet_errors, registry, uprint
  File "/usr/local/lib/python3.6/site-packages/isbntools/app.py", line 16, in <module>
    from ._initapp import config, registry, CONF_PATH, CACHE_FILE
  File "/usr/local/lib/python3.6/site-packages/isbntools/_initapp.py", line 154, in <module>
    logging.basicConfig(filename=log_path, level=level, format=fmt)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1806, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/stefan/isbntools/isbntools.log'
```
I am running Python 3.6.4 on OS X 10.11.6

**Comment by xlcnd** [comment]
Hi, 

I am not able to reproduce this error (but I don't have access to a machine running Python 3.6.4 on OS X 10.11.6)!  Anyway... can you tell me if the directory '/Users/stefan/isbntools/' exists in your system? And if 'Yes', could you create the file 'isbntools.log' inside it and check if the error continues?

**Comment by dhimmel** [comment]
I'm also getting this error:

```
Traceback (most recent call last):
  File "/home/dhimmel/anaconda3/bin/isbn_meta", line 7, in <module>
    from isbntools.bin.meta import main
  File "/home/dhimmel/anaconda3/lib/python3.6/site-packages/isbntools/bin/meta.py", line 6, in <module>
    from ..app import (canonical, clean, config, get_canonical_isbn, meta,
  File "/home/dhimmel/anaconda3/lib/python3.6/site-packages/isbntools/app.py", line 16, in <module>
    from ._initapp import config, registry, CONF_PATH, CACHE_FILE
  File "/home/dhimmel/anaconda3/lib/python3.6/site-packages/isbntools/_initapp.py", line 153, in <module>
    logging.basicConfig(filename=log_path, level=level, format=fmt)
  File "/home/dhimmel/anaconda3/lib/python3.6/logging/__init__.py", line 1806, in basicConfig
    h = FileHandler(filename, mode)
  File "/home/dhimmel/anaconda3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/dhimmel/anaconda3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dhimmel/isbntools/isbntools.log'
```

I don't want this utility to be writing files... is there a reason why having this log file is required?

**Comment by xlcnd** [comment]
This tool NEEDS to write files (for config, log, cache, ...) grouped inside a folder named `isbntools` or `.isbntools`. That is why is advisable to install it inside a virtual environment and not install it system wide. If you don't need or don't want it to write files, probably you don't need `isbntools`just use `isbnlib`. 

Some systems (see #87) don't allow the installer to write files in the user's space and some installers (`conda` ?) seem not to do it too. In that case the only solution is to create the folder manually (see #87 again).

Why don't you make all these files optional? In some way they are, however they need to be defined first by the installer and the user, location, permissions and protections be established. Then you can choose what to use. The alternative is to run the code for this *each time you run any* `isbntools` *command*!

**Comment by workflowsguy** [comment]
After manually creating an ~/ISBNTOOLS folder, no more errors are thrown.
However, I am confused.
On another Mac where I installed `isbntools` some time ago, the folder ~/.isbntools is used, as expected.

So when I create this directory on the newer machine, `isbntools` now switches to using this directory (~/.isbntools) instead of ~/ISBNTOOLS. (I deleted the latter, and `isbntools` still work).

My question is: why does `isbntools` no longer simply create ~/.isbntools like it did earlier?

**Comment by xlcnd** [comment]
Thanks! The place where the folder (`isbntools` or `.isbntools`) his created is a mixture of os system, python version and installer used (pip, easy_install, conda, ...), options passed to installer (local, user, ...) and if is inside a virtual environment or not, however there is a finite list of possibilities. So the setup file gives the order to create the folder and `isbntools` searches the different possible paths to find a suitable folder (but with some preferences defined, e.g., if the situation asks for `.isbntools` folder and there are a `isbntools`folder it will use the first if exists and the later otherwise). That explains the above behavior that you reported. However doesn't explain: 

1. why `.isbntools` wasn't created by the installer (no clue, usually is an os thing and I cannot do nothing... my advice is to install the package inside a virtual environment)
2. why the program searched for `isbntools` instead of `.isbntools`. For that I found a regression error introduced by a 'release' script in `isbntools-4.3.7`, and is now solved.

Tomorrow I will release a new version to fix the problem. 

Thanks again.

**Comment by xlcnd** [comment]
Version v4.3.10 is now out with the bug fixed.

**Comment by workflowsguy** [comment]
I just verified that `isbntools-4.3.11` now creates and writes `~/.isbntools` correctly.
The only weird thing is that `pip3 install isbntools -U` fails with a permissions error.
If I run the command with `sudo`, it works (here's hoping that this doesn't cause something else to fail..).

Anyway, thanks!

**Comment by xlcnd** [comment]
I don't know what the default behavior for OS X is, but for most of the linux distributions you need `sudo` to `pip install` packages system-wide! You can always make a 'local' install with `pip3 install isbntools --user --update`.

Thanks!

**Comment by xlcnd** [comment]
I think the problem is now solved... 

Thanks  @workflowsguy and @dhimmel!
