### ISSUE TITLE
Find ISBNs from list of Authors + Titles

### ISSUE THREAD

**Issue by remyrascal** [xlcnd/isbntools#99]
Is there anyway that i can use the `Isbn_from_words` command on a list of authors and titles and get an output file with the list of isbns?

Any help is greatly appreciated I have a list of 13000 books that i need to organize and i dont have the time to look up the isbn for each book

**Comment by xlcnd** [comment]
`isbn_from_words "words from title and author name"` is the only syntax accepted by this command, however you can use this command inside a script  (bash, cmd, python, ...) that runs over your list.

**N.B.:** You must process just a few hundred books per day or Google will block you!

**Comment by abhimanyudhawan** [comment]
Is isbndb supported in isbntools 4.3.15? The documentation doesn't show that..

**Comment by xlcnd** [comment]
`isbndb` is not supported by `isbnlib` since it dropped the free subscription.
